name: Backend and Frontend Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

  deploy-backend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.backend == 'true' || contains(github.event.head_commit.message, 'deploy-backend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: SSH into VPS and Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.VPS_IP }}
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                cd /var/www/workout-tracker
                git pull origin main
                docker compose --env-file ./backend/.env up --build -d backend
                docker system prune -f

  deploy-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' || contains(github.event.head_commit.message, 'deploy-frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for backend deployment
        if: ${{ needs.check-changes.outputs.backend == 'true' || contains(github.event.head_commit.message, 'deploy-backend') }}
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'deploy-backend'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: SSH into VPS and Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.VPS_IP }}
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                cd /var/www/workout-tracker
                git pull origin main
                docker compose --env-file ./backend/.env build --build-arg BUILDKIT_INLINE_CACHE=1 frontend
                docker compose --env-file ./backend/.env up -d frontend
                docker system prune -f
