name: Deploy Frontend of Workout Tracker

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and Deploy Project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/workout-tracker

            # Pull the latest changes from the repository
            git pull origin main

            # build and run frontend
            docker-compose up --build -d frontend
